In [23]:
import pandas as pd
import numpy as np

In [27]:
df_may = pd.read_csv(r"data/May.csv")

date_cols = [col for col in df_may.columns if "/" in col]

df_long = pd.melt(
    df_may,
    id_vars=["WD EID", "Emp Name"],
    value_vars=date_cols,
    var_name="temp_col",
    value_name="val",
)

df_long[["Date", "Metric"]] = df_long["temp_col"].str.rsplit(
    "_", n=1, expand=True
)
df_long = df_long.drop(columns=["temp_col"])

df_final_5 = df_long.pivot_table(
    index=["WD EID", "Emp Name", "Date"],
    columns="Metric",
    values="val"
).reset_index()


df_final_5.reindex(columns=["WD EID", "Emp Name", "Date", "Answered", "AHT"])

Metric     WD EID          Emp Name       Date  Answered    AHT
0       102496670         Dieu Tien  5/17/2026      60.0  452.0
1       102496670         Dieu Tien  5/18/2026      60.0  451.0
2       102496670         Dieu Tien  5/19/2026      70.0  414.0
3       102496670         Dieu Tien  5/22/2026      70.0  406.0
4       102496670         Dieu Tien  5/23/2026      55.0  412.0
..            ...               ...        ...       ...    ...
282     103477990  Le Duy Thu Huyen  5/25/2026      30.0  906.0
283     103477990  Le Duy Thu Huyen  5/26/2026      30.0  887.0
284     103477990  Le Duy Thu Huyen  5/27/2026      31.0  861.0
285     103477990  Le Duy Thu Huyen  5/30/2026      32.0  850.0
286     103477990  Le Duy Thu Huyen  5/31/2026      29.0  907.0

[287 rows x 5 columns]

In [25]:
df_june = pd.read_csv(r"data/June.csv")

date_cols = [col for col in df_june.columns if "/" in col]

df_long = pd.melt(
    df_june,
    id_vars=["WD EID", "Emp Name"],
    value_vars=date_cols,
    var_name="temp_col",
    value_name="val",
)

df_long[["Date", "Metric"]] = df_long["temp_col"].str.rsplit(
    "_", n=1, expand=True
)
df_long = df_long.drop(columns=["temp_col"])

df_final_6 = df_long.pivot_table(
    index=["WD EID", "Emp Name", "Date"],
    columns="Metric",
    values="val"
).reset_index()


df_final_6.reindex(columns=["WD EID", "Emp Name", "Date", "Answered", "AHT"])

Metric     WD EID          Emp Name       Date  Answered    AHT
0       102496670         Dieu Tien  6/12/2026      62.0  427.0
1       102496670         Dieu Tien  6/13/2026      49.0  479.0
2       102496670         Dieu Tien  6/14/2026      57.0  479.0
3       102496670         Dieu Tien  6/15/2026      53.0  516.0
4       102496670         Dieu Tien  6/16/2026      58.0  487.0
..            ...               ...        ...       ...    ...
417     103477990  Le Duy Thu Huyen  6/26/2026      42.0  630.0
418     103477990  Le Duy Thu Huyen  6/29/2026      46.0  571.0
419     103477990  Le Duy Thu Huyen  6/30/2026      48.0  548.0
420     103477990  Le Duy Thu Huyen   6/8/2026      42.0  646.0
421     103477990  Le Duy Thu Huyen   6/9/2026      47.0  570.0

[422 rows x 5 columns]

In [30]:
df_july = pd.read_csv(r"data/July.csv")

date_cols = [col for col in df_july.columns if "/" in col]

df_long = pd.melt(
    df_july,
    id_vars=["WD EID", "Emp Name"],
    value_vars=date_cols,
    var_name="temp_col",
    value_name="val",
)

df_long[["Date", "Metric"]] = df_long["temp_col"].str.rsplit(
    "_", n=1, expand=True
)
df_long = df_long.drop(columns=["temp_col"])

df_final_7 = df_long.pivot_table(
    index=["WD EID", "Emp Name", "Date"],
    columns="Metric",
    values="val"
).reset_index()


df_final_7.reindex(columns=["WD EID", "Emp Name", "Date", "Answered", "AHT"])

Metric     WD EID          Emp Name       Date  Answered    AHT
0       102496670         Dieu Tien  7/11/2026      75.0  359.0
1       102496670         Dieu Tien  7/12/2026      80.0  338.0
2       102496670         Dieu Tien  7/13/2026      83.0  323.0
3       102496670         Dieu Tien  7/14/2026      53.0  381.0
4       102496670         Dieu Tien  7/15/2026      90.0  298.0
..            ...               ...        ...       ...    ...
266     103477990  Le Duy Thu Huyen  7/20/2026      50.0  522.0
267     103477990  Le Duy Thu Huyen  7/21/2026      53.0  485.0
268     103477990  Le Duy Thu Huyen  7/22/2026      51.0  504.0
269     103477990  Le Duy Thu Huyen   7/8/2026      48.0  551.0
270     103477990  Le Duy Thu Huyen   7/9/2026      48.0  545.0

[271 rows x 5 columns]

In [ ]:
df = pd.concat([df_final_5, df_final_6], ignore_index=True)

df[df["Emp Name"] == "Dieu Tien"]

Metric     WD EID   Emp Name       Date    AHT  Answered
0       102496670  Dieu Tien  5/17/2026  452.0      60.0
1       102496670  Dieu Tien  5/18/2026  451.0      60.0
2       102496670  Dieu Tien  5/19/2026  414.0      70.0
3       102496670  Dieu Tien  5/22/2026  406.0      70.0
4       102496670  Dieu Tien  5/23/2026  412.0      55.0
5       102496670  Dieu Tien  5/24/2026  521.0      53.0
6       102496670  Dieu Tien  5/25/2026  502.0      55.0
7       102496670  Dieu Tien  5/26/2026  409.0      65.0
8       102496670  Dieu Tien  5/29/2026  496.0      57.0
9       102496670  Dieu Tien  5/30/2026  470.0      57.0
10      102496670  Dieu Tien  5/31/2026  448.0      60.0
287     102496670  Dieu Tien  6/12/2026  427.0      62.0
288     102496670  Dieu Tien  6/13/2026  479.0      49.0
289     102496670  Dieu Tien  6/14/2026  479.0      57.0
290     102496670  Dieu Tien  6/15/2026  516.0      53.0
291     102496670  Dieu Tien  6/16/2026  487.0      58.0
292     102496670  Dieu Tien  6/19/2026  442.0      62.0
293     102496670  Dieu Tien  6/21/2026  454.0      56.0
294     102496670  Dieu Tien  6/22/2026  450.0      60.0
295     102496670  Dieu Tien  6/25/2026  416.0      65.0
296     102496670  Dieu Tien  6/26/2026  443.0      62.0
297     102496670  Dieu Tien  6/27/2026  387.0      70.0
298     102496670  Dieu Tien  6/28/2026  347.0      76.0
299     102496670  Dieu Tien  6/29/2026  509.0      53.0
300     102496670  Dieu Tien  6/30/2026  441.0      62.0
301     102496670  Dieu Tien   6/8/2026  400.0      36.0
302     102496670  Dieu Tien   6/9/2026  411.0      67.0

In [101]:
df = pd.read_csv("data/Work_Schedule(6-7).csv")

date_cols = [col for col in df.columns if "/" in col]

df_long = pd.melt(
    df,
    id_vars=["Employee ID", "Employee Name"],
    value_vars=date_cols,
    var_name="temp_col",
    value_name="val",
)

df_long = df_long.assign(
    Month = df_long.temp_col.str[:1:],
    Year = df_long.temp_col.str[-4::]
)

df_long[df_long["Employee Name"] == "Nguyen Thi Phuong Thuy Nguyen"]

,Employee ID,Employee Name,temp_col,val,Month,Year
1,102496681,Nguyen Thi Phuong Thuy Nguyen,6/6/2026,WO-WO,6,2026
27,102496681,Nguyen Thi Phuong Thuy Nguyen,6/7/2026,WO-WO,6,2026
53,102496681,Nguyen Thi Phuong Thuy Nguyen,6/8/2026,11:00-20:00,6,2026
79,102496681,Nguyen Thi Phuong Thuy Nguyen,6/9/2026,11:00-20:00,6,2026
105,102496681,Nguyen Thi Phuong Thuy Nguyen,6/10/2026,11:00-20:00,6,2026
131,102496681,Nguyen Thi Phuong Thuy Nguyen,6/11/2026,11:00-20:00,6,2026
157,102496681,Nguyen Thi Phuong Thuy Nguyen,6/12/2026,11:00-20:00,6,2026
183,102496681,Nguyen Thi Phuong Thuy Nguyen,6/13/2026,WO-WO,6,2026
209,102496681,Nguyen Thi Phuong Thuy Nguyen,6/14/2026,WO-WO,6,2026
235,102496681,Nguyen Thi Phuong Thuy Nguyen,6/15/2026,11:00-20:00,6,2026
261,102496681,Nguyen Thi Phuong Thuy Nguyen,6/16/2026,11:00-20:00,6,2026
287,102496681,Nguyen Thi Phuong Thuy Nguyen,6/17/2026,11:00-20:00,6,2026
313,102496681,Nguyen Thi Phuong Thuy Nguyen,6/18/2026,11:00-20:00,6,2026
339,102496681,Nguyen Thi Phuong Thuy Nguyen,6/19/2026,11:00-20:00,6,2026
365,102496681,Nguyen Thi Phuong Thuy Nguyen,6/20/2026,WO-WO,6,2026
391,102496681,Nguyen Thi Phuong Thuy Nguyen,6/21/2026,WO-WO,6,2026
417,102496681,Nguyen Thi Phuong Thuy Nguyen,6/22/2026,11:00-20:00,6,2026
443,102496681,Nguyen Thi Phuong Thuy Nguyen,6/23/2026,11:00-20:00,6,2026
469,102496681,Nguyen Thi Phuong Thuy Nguyen,6/24/2026,11:00-20:00,6,2026
495,102496681,Nguyen Thi Phuong Thuy Nguyen,6/25/2026,WO-WO,6,2026
521,102496681,Nguyen Thi Phuong Thuy Nguyen,6/26/2026,WO-WO,6,2026
547,102496681,Nguyen Thi Phuong Thuy Nguyen,6/27/2026,11:00-20:00,6,2026
573,102496681,Nguyen Thi Phuong Thuy Nguyen,6/28/2026,HAL_UP,6,2026
599,102496681,Nguyen Thi Phuong Thuy Nguyen,6/29/2026,11:00-20:00,6,2026
625,102496681,Nguyen Thi Phuong Thuy Nguyen,6/30/2026,11:00-20:00,6,2026
651,102496681,Nguyen Thi Phuong Thuy Nguyen,7/1/2026,11:00-20:00,7,2026
677,102496681,Nguyen Thi Phuong Thuy Nguyen,7/2/2026,11:00-20:00,7,2026
703,102496681,Nguyen Thi Phuong Thuy Nguyen,7/3/2026,11:00-20:00,7,2026
729,102496681,Nguyen Thi Phuong Thuy Nguyen,7/4/2026,WO-WO,7,2026
755,102496681,Nguyen Thi Phuong Thuy Nguyen,7/5/2026,WO-WO,7,2026
781,102496681,Nguyen Thi Phuong Thuy Nguyen,7/6/2026,21:00-06:00,7,2026
807,102496681,Nguyen Thi Phuong Thuy Nguyen,7/7/2026,21:00-06:00,7,2026
833,102496681,Nguyen Thi Phuong Thuy Nguyen,7/8/2026,21:00-06:00,7,2026
859,102496681,Nguyen Thi Phuong Thuy Nguyen,7/9/2026,21:00-06:00,7,2026
885,102496681,Nguyen Thi Phuong Thuy Nguyen,7/10/2026,21:00-06:00,7,2026
911,102496681,Nguyen Thi Phuong Thuy Nguyen,7/11/2026,WO-WO,7,2026
937,102496681,Nguyen Thi Phuong Thuy Nguyen,7/12/2026,WO-WO,7,2026
963,102496681,Nguyen Thi Phuong Thuy Nguyen,7/13/2026,21:00-06:00,7,2026
989,102496681,Nguyen Thi Phuong Thuy Nguyen,7/14/2026,21:00-06:00,7,2026
1015,102496681,Nguyen Thi Phuong Thuy Nguyen,7/15/2026,21:00-06:00,7,2026
1041,102496681,Nguyen Thi Phuong Thuy Nguyen,7/16/2026,21:00-06:00,7,2026
1067,102496681,Nguyen Thi Phuong Thuy Nguyen,7/17/2026,21:00-06:00,7,2026
1093,102496681,Nguyen Thi Phuong Thuy Nguyen,7/18/2026,WO-WO,7,2026
1119,102496681,Nguyen Thi Phuong Thuy Nguyen,7/19/2026,WO-WO,7,2026
1145,102496681,Nguyen Thi Phuong Thuy Nguyen,7/20/2026,21:00-06:00,7,2026
1171,102496681,Nguyen Thi Phuong Thuy Nguyen,7/21/2026,21:00-06:00,7,2026
1197,102496681,Nguyen Thi Phuong Thuy Nguyen,7/22/2026,21:00-06:00,7,2026
1223,102496681,Nguyen Thi Phuong Thuy Nguyen,7/23/2026,21:00-06:00,7,2026
1249,102496681,Nguyen Thi Phuong Thuy Nguyen,7/24/2026,21:00-06:00,7,2026
1275,102496681,Nguyen Thi Phuong Thuy Nguyen,7/25/2026,WO-WO,7,2026
1301,102496681,Nguyen Thi Phuong Thuy Nguyen,7/26/2026,WO-WO,7,2026
1327,102496681,Nguyen Thi Phuong Thuy Nguyen,7/27/2026,21:00-06:00,7,2026
1353,102496681,Nguyen Thi Phuong Thuy Nguyen,7/28/2026,21:00-06:00,7,2026
1379,102496681,Nguyen Thi Phuong Thuy Nguyen,7/29/2026,21:00-06:00,7,2026
1405,102496681,Nguyen Thi Phuong Thuy Nguyen,7/30/2026,21:00-06:00,7,2026
1431,102496681,Nguyen Thi Phuong Thuy Nguyen,7/31/2026,21:00-06:00,7,2026
1457,102496681,Nguyen Thi Phuong Thuy Nguyen,8/1/2026,WO-WO,8,2026
1483,102496681,Nguyen Thi Phuong Thuy Nguyen,8/2/2026,WO-WO,8,2026

In [125]:
shift_map = {
    "06:00-15:00": "Day",
    "11:00-20:00": "Noon",
    "12:00-21:00": "Noon",
    "21:00-06:00": "Night"
}

df_long["Shift"] = df_long["val"].map(shift_map)

df_schedule = df_long.reindex(columns=["Employee ID", "Employee Name", "Month", "Year", "Shift"]).sort_values(["Employee ID", "Employee Name", "Month", "Year"])

df_schedule = df_schedule.dropna().groupby(["Employee ID", "Employee Name", "Month", "Year", "Shift"]).agg(
    shift_count = ("Shift", "count")
).reset_index()

df_schedule = df_schedule.sort_values(["Employee ID", "Employee Name", "Month", "Year", "shift_count"], ascending=[True, True, True, True, False]).drop_duplicates(subset=["Employee ID", "Employee Name", "Month", "Year"], keep="first")

df_schedule = df_schedule.astype({"Month": "int16", "Year":"int16"})

df_schedule[df_schedule.Month != 8]

,Employee ID,Employee Name,Month,Year,Shift,shift_count
0,102496670,Dieu Tien,6,2026,Day,17
2,102496670,Dieu Tien,7,2026,Noon,17
4,102496681,Nguyen Thi Phuong Thuy Nguyen,6,2026,Noon,16
5,102496681,Nguyen Thi Phuong Thuy Nguyen,7,2026,Night,20
7,102845218,Nguyen Ngoc Anh Thu,6,2026,Noon,17
8,102845218,Nguyen Ngoc Anh Thu,7,2026,Noon,20
10,102893381,Vu Van Khang,6,2026,Night,17
11,102893381,Vu Van Khang,7,2026,Night,24
12,102972298,Nguyen Thi Bich Ngan,6,2026,Day,13
13,102972298,Nguyen Thi Bich Ngan,7,2026,Day,4
14,103193904,Vuong Hoang Bao,6,2026,Night,15
15,103193904,Vuong Hoang Bao,7,2026,Day,13
18,103222889,Le Hau,6,2026,Night,16
19,103222889,Le Hau,7,2026,Night,22
21,103286054,Nguyen Y Bao Han,6,2026,Night,16
22,103286054,Nguyen Y Bao Han,7,2026,Night,19
24,103293621,Nguyen Tran Anh Tu,6,2026,Night,13
26,103293621,Nguyen Tran Anh Tu,7,2026,Night,20
28,103304193,Truong Thi Thanh Tam,6,2026,Day,18
29,103304193,Truong Thi Thanh Tam,7,2026,Day,19
30,103309812,Tran Hoang Anh,6,2026,Noon,14
31,103309812,Tran Hoang Anh,7,2026,Day,18
33,103310980,Nguyen Thuy Duong,6,2026,Night,12
34,103310980,Nguyen Thuy Duong,7,2026,Night,17
36,103311553,Tran Duc Binh,6,2026,Day,19
37,103311553,Tran Duc Binh,7,2026,Day,20
39,103324502,Tran Nguyen Hoang Trieu,6,2026,Noon,16
40,103324502,Tran Nguyen Hoang Trieu,7,2026,Noon,21
42,103338101,Le Phi Hoang,6,2026,Noon,18
43,103338101,Le Phi Hoang,7,2026,Noon,20
45,103338297,Cao Minh Hoang,6,2026,Noon,18
46,103338297,Cao Minh Hoang,7,2026,Noon,22
48,103345473,Nguyen Duc Thuan,6,2026,Noon,18
49,103345473,Nguyen Duc Thuan,7,2026,Noon,19
51,103431523,Tran Thanh Viet Ha,6,2026,Noon,17
52,103431523,Tran Thanh Viet Ha,7,2026,Noon,23
54,103455199,Nguyen Tran Khuong Duy,6,2026,Noon,18
55,103455199,Nguyen Tran Khuong Duy,7,2026,Night,17
59,103455202,Huynh Le Thuy Thanh,6,2026,Noon,14
60,103455202,Huynh Le Thuy Thanh,7,2026,Noon,20
62,103455211,Vo Truong Trong Tin,6,2026,Noon,17
63,103455211,Vo Truong Trong Tin,7,2026,Day,17
67,103455214,Nguyen Ngoc My Kim,6,2026,Day,15
69,103455214,Nguyen Ngoc My Kim,7,2026,Day,21
71,103456015,Nguyen Ngoc Thanh Tam,6,2026,Night,17
72,103456015,Nguyen Ngoc Thanh Tam,7,2026,Night,22
73,103471626,Nguyen Ho Minh Dai,6,2026,Night,15
74,103471626,Nguyen Ho Minh Dai,7,2026,Night,10
75,103477971,Nguyen Ngoc Quynh Giang,6,2026,Noon,17
76,103477971,Nguyen Ngoc Quynh Giang,7,2026,Noon,20
78,103477990,Le Duy Thu Huyen,6,2026,Noon,17
80,103477990,Le Duy Thu Huyen,7,2026,Noon,11

In [51]:
test = pd.DataFrame({"col":["6/6/2026"]})

test["check"] = test.col.str[4::]

test

        col check
0  6/6/2026  2026